// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	stock "gateway/biz/router/stock"
	trade "gateway/biz/router/trade"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	trade.Register(r)

	stock.Register(r)
}
