# 开发环境配置

server:
  host: "0.0.0.0"
  port: 8000
  debug: true

database:
  mysql:
    host: "localhost"
    port: 3306
    username: "dev_user"
    password: "dev_password"
    database: "lang_example_dev"

  redis:
    host: "localhost"
    port: 6379
    db: 0