# 生产环境配置

server:
  host: "0.0.0.0"
  port: 8000
  debug: false

database:
  mysql:
    host: "prod-db-host"
    port: 3306
    username: "prod_user"
    password: "prod_password"
    database: "lang_example_prod"

  redis:
    host: "prod-redis-host"
    port: 6379
    db: 0