// Code generated by hertz generator.

package stock

import (
	"context"

	stock "gateway/biz/model/stock"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetStockTradeData .
// @router /api/v1/stock/:symbol/date/:date [GET]
func GetStockTradeData(ctx context.Context, c *app.RequestContext) {
	var err error
	var req stock.GetStockTradeDataRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(stock.GetStockTradeDataResponse)

	c.JSON(consts.StatusOK, resp)
}
