// Code generated by hertz generator.

package stock

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _stockMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _symbolMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dateMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getstocktradedataMw() []app.HandlerFunc {
	// your code...
	return nil
}
