// Code generated by Kitex v0.15.0. DO NOT EDIT.

package accountservice

import (
	account "cloudewego/kitex_gen/trade/account"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	QueryPositions(ctx context.Context, Req *account.QueryPositionsRequest, callOptions ...callopt.Option) (r *account.QueryPositionsResponse, err error)
	QueryAccount(ctx context.Context, Req *account.QueryAccountRequest, callOptions ...callopt.Option) (r *account.QueryAccountResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kAccountServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kAccountServiceClient struct {
	*kClient
}

func (p *kAccountServiceClient) QueryPositions(ctx context.Context, Req *account.QueryPositionsRequest, callOptions ...callopt.Option) (r *account.QueryPositionsResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryPositions(ctx, Req)
}

func (p *kAccountServiceClient) QueryAccount(ctx context.Context, Req *account.QueryAccountRequest, callOptions ...callopt.Option) (r *account.QueryAccountResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryAccount(ctx, Req)
}
