// Code generated by Kitex v0.15.0. DO NOT EDIT.

package strategyservice

import (
	strategy "cloudewego/kitex_gen/strategy"
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "github.com/cloudwego/prutal"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"QueryStrategySelected": kitex.NewMethodInfo(
		queryStrategySelectedHandler,
		newQueryStrategySelectedArgs,
		newQueryStrategySelectedResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	strategyServiceServiceInfo                = NewServiceInfo()
	strategyServiceServiceInfoForClient       = NewServiceInfoForClient()
	strategyServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return strategyServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return strategyServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return strategyServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "StrategyService"
	handlerType := (*strategy.StrategyService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "strategy",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.15.0",
		Extra:           extra,
	}
	return svcInfo
}

func queryStrategySelectedHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(strategy.QueryStrategySelectedReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(strategy.StrategyService).QueryStrategySelected(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *QueryStrategySelectedArgs:
		success, err := handler.(strategy.StrategyService).QueryStrategySelected(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*QueryStrategySelectedResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newQueryStrategySelectedArgs() interface{} {
	return &QueryStrategySelectedArgs{}
}

func newQueryStrategySelectedResult() interface{} {
	return &QueryStrategySelectedResult{}
}

type QueryStrategySelectedArgs struct {
	Req *strategy.QueryStrategySelectedReq
}

func (p *QueryStrategySelectedArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *QueryStrategySelectedArgs) Unmarshal(in []byte) error {
	msg := new(strategy.QueryStrategySelectedReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var QueryStrategySelectedArgs_Req_DEFAULT *strategy.QueryStrategySelectedReq

func (p *QueryStrategySelectedArgs) GetReq() *strategy.QueryStrategySelectedReq {
	if !p.IsSetReq() {
		return QueryStrategySelectedArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *QueryStrategySelectedArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *QueryStrategySelectedArgs) GetFirstArgument() interface{} {
	return p.Req
}

type QueryStrategySelectedResult struct {
	Success *strategy.QueryStrategySelectedRes
}

var QueryStrategySelectedResult_Success_DEFAULT *strategy.QueryStrategySelectedRes

func (p *QueryStrategySelectedResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *QueryStrategySelectedResult) Unmarshal(in []byte) error {
	msg := new(strategy.QueryStrategySelectedRes)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *QueryStrategySelectedResult) GetSuccess() *strategy.QueryStrategySelectedRes {
	if !p.IsSetSuccess() {
		return QueryStrategySelectedResult_Success_DEFAULT
	}
	return p.Success
}

func (p *QueryStrategySelectedResult) SetSuccess(x interface{}) {
	p.Success = x.(*strategy.QueryStrategySelectedRes)
}

func (p *QueryStrategySelectedResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *QueryStrategySelectedResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) QueryStrategySelected(ctx context.Context, Req *strategy.QueryStrategySelectedReq) (r *strategy.QueryStrategySelectedRes, err error) {
	var _args QueryStrategySelectedArgs
	_args.Req = Req
	var _result QueryStrategySelectedResult
	if err = p.c.Call(ctx, "QueryStrategySelected", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
