// Code generated by Kitex v0.15.0. DO NOT EDIT.

package stocktradeservice

import (
	trade "cloudewego/kitex_gen/stock/trade"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	streamcall "github.com/cloudwego/kitex/client/callopt/streamcall"
	streamclient "github.com/cloudwego/kitex/client/streamclient"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	transport "github.com/cloudwego/kitex/transport"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetStockTradeData(ctx context.Context, Req *trade.GetStockTradeDataReq, callOptions ...callopt.Option) (r *trade.GetStockTradeDataRes, err error)
	StreamTradeData(ctx context.Context, Req *trade.StreamTradeDataReq, callOptions ...callopt.Option) (stream StockTradeService_StreamTradeDataClient, err error)
}

// StreamClient is designed to provide Interface for Streaming APIs.
type StreamClient interface {
	StreamTradeData(ctx context.Context, Req *trade.StreamTradeDataReq, callOptions ...streamcall.Option) (stream StockTradeService_StreamTradeDataClient, err error)
}

type StockTradeService_StreamTradeDataClient interface {
	streaming.Stream
	Recv() (*trade.StreamTradeDataRes, error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, client.WithTransportProtocol(transport.GRPC))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kStockTradeServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kStockTradeServiceClient struct {
	*kClient
}

func (p *kStockTradeServiceClient) GetStockTradeData(ctx context.Context, Req *trade.GetStockTradeDataReq, callOptions ...callopt.Option) (r *trade.GetStockTradeDataRes, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetStockTradeData(ctx, Req)
}

func (p *kStockTradeServiceClient) StreamTradeData(ctx context.Context, Req *trade.StreamTradeDataReq, callOptions ...callopt.Option) (stream StockTradeService_StreamTradeDataClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.StreamTradeData(ctx, Req)
}

// NewStreamClient creates a stream client for the service's streaming APIs defined in IDL.
func NewStreamClient(destService string, opts ...streamclient.Option) (StreamClient, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))
	options = append(options, client.WithTransportProtocol(transport.GRPC))
	options = append(options, streamclient.GetClientOptions(opts)...)

	kc, err := client.NewClient(serviceInfoForStreamClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kStockTradeServiceStreamClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewStreamClient creates a stream client for the service's streaming APIs defined in IDL.
// It panics if any error occurs.
func MustNewStreamClient(destService string, opts ...streamclient.Option) StreamClient {
	kc, err := NewStreamClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kStockTradeServiceStreamClient struct {
	*kClient
}

func (p *kStockTradeServiceStreamClient) StreamTradeData(ctx context.Context, Req *trade.StreamTradeDataReq, callOptions ...streamcall.Option) (stream StockTradeService_StreamTradeDataClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, streamcall.GetCallOptions(callOptions))
	return p.kClient.StreamTradeData(ctx, Req)
}
