// Code generated by hertz generator.

package trade

import (
	"context"

	trade "gateway/biz/model/trade"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// CreateTrade .
// @router /api/v1/trade [POST]
func CreateTrade(ctx context.Context, c *app.RequestContext) {
	var err error
	var req trade.CreateTradeRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(trade.CreateTradeResponse)

	c.JSON(consts.StatusOK, resp)
}
